// Comprehensive Japanese dictionary for these songs.
// Used for maximum-matching tokenization — any word clicked in the lyrics
// that isn't in the song's key/extended vocab will look up here.
// Format: 'ja': { romaji, en, hiragana? }

const JDICT = new Map(Object.entries({
  // ── Particles & grammar markers ───────────────────────────────
  'が': { romaji: 'ga', en: 'subject marker', hiragana: 'が' },
  'を': { romaji: 'wo', en: 'object marker', hiragana: 'を' },
  'は': { romaji: 'wa', en: 'topic marker', hiragana: 'は' },
  'に': { romaji: 'ni', en: 'direction / location / time marker', hiragana: 'に' },
  'で': { romaji: 'de', en: 'location of action / by means of', hiragana: 'で' },
  'と': { romaji: 'to', en: 'and / with / quotation marker', hiragana: 'と' },
  'の': { romaji: 'no', en: 'possessive / nominalizer', hiragana: 'の' },
  'も': { romaji: 'mo', en: 'also / even / too', hiragana: 'も' },
  'から': { romaji: 'kara', en: 'from / because / since', hiragana: 'から' },
  'まで': { romaji: 'made', en: 'until / up to / as far as', hiragana: 'まで' },
  'より': { romaji: 'yori', en: 'than / from (formal)', hiragana: 'より' },
  'へ': { romaji: 'e', en: 'toward / to (direction)', hiragana: 'へ' },
  'か': { romaji: 'ka', en: 'question marker / or', hiragana: 'か' },
  'ね': { romaji: 'ne', en: 'seeking agreement: "isn\'t it?" / "right?"', hiragana: 'ね' },
  'よ': { romaji: 'yo', en: 'assertion marker: "I\'m telling you" / "you know"', hiragana: 'よ' },
  'な': { romaji: 'na', en: 'casual sentence-ending / "right?"', hiragana: 'な' },
  'さ': { romaji: 'sa', en: 'casual assertion: "of course" / "you see"', hiragana: 'さ' },
  'ぞ': { romaji: 'zo', en: 'strong assertion (masculine): "I tell you!"', hiragana: 'ぞ' },
  'って': { romaji: 'tte', en: 'quotation / casual topic marker: "they say…"', hiragana: 'って' },
  'けど': { romaji: 'kedo', en: 'but / although / however', hiragana: 'けど' },
  'だけ': { romaji: 'dake', en: 'only / just / merely', hiragana: 'だけ' },
  'ほど': { romaji: 'hodo', en: 'to the extent of / as much as', hiragana: 'ほど' },
  'など': { romaji: 'nado', en: 'etc. / and so on / things like', hiragana: 'など' },
  'なんて': { romaji: 'nante', en: 'things like / I can\'t believe / how could (dismissive)', hiragana: 'なんて', example: '君の顔なんて忘れてやるさ', exampleEn: 'I\'ll forget your face — as if!' },
  'この': { romaji: 'kono', en: 'this (before a noun)', hiragana: 'この', example: 'この歌が好き', exampleEn: 'I like this song' },
  'ながら': { romaji: 'nagara', en: 'while doing (two actions simultaneously)', hiragana: 'ながら' },
  'たびに': { romaji: 'tabi ni', en: 'every time / whenever', hiragana: 'たびに' },
  'ばかり': { romaji: 'bakari', en: 'only / nothing but / just finished', hiragana: 'ばかり' },
  'ばっか': { romaji: 'bakka', en: 'nothing but (casual ばかり)', hiragana: 'ばっか' },
  'みたい': { romaji: 'mitai', en: 'seems like / looks like / similar to', hiragana: 'みたい' },
  'らしい': { romaji: 'rashii', en: 'seems like / I hear that / typical of', hiragana: 'らしい' },
  'そう': { romaji: 'sō', en: 'it seems / looks like (appearance)', hiragana: 'そう' },
  'ので': { romaji: 'node', en: 'because / since (reason)', hiragana: 'ので' },
  'のに': { romaji: 'noni', en: 'even though / despite / and yet', hiragana: 'のに' },
  'ても': { romaji: 'temo', en: 'even if / even though', hiragana: 'ても' },
  'でも': { romaji: 'demo', en: 'but / however / even', hiragana: 'でも' },
  'だから': { romaji: 'dakara', en: 'therefore / that\'s why / so', hiragana: 'だから' },
  'だけど': { romaji: 'dakedo', en: 'but / however (casual)', hiragana: 'だけど' },
  'しかも': { romaji: 'shikamo', en: 'moreover / furthermore', hiragana: 'しかも' },
  'だって': { romaji: 'datte', en: 'but / because / even (casual)', hiragana: 'だって' },
  'だろ': { romaji: 'daro', en: 'right? / isn\'t it? (casual)', hiragana: 'だろ' },
  'かな': { romaji: 'kana', en: 'I wonder… / maybe… (soft question)', hiragana: 'かな' },
  'のかな': { romaji: 'no kana', en: 'I wonder if…', hiragana: 'のかな' },
  'のか': { romaji: 'no ka', en: 'whether… / is it that…?', hiragana: 'のか' },
  'ものか': { romaji: 'mono ka', en: 'as if I would! / no way!', hiragana: 'ものか' },
  'ものを': { romaji: 'mono wo', en: 'even though / and yet…', hiragana: 'ものを' },

  // ── Auxiliaries & verb endings ────────────────────────────────
  'いる': { romaji: 'iru', en: 'to be / to exist (animate)', hiragana: 'いる' },
  'いた': { romaji: 'ita', en: 'was / were (animate, past)', hiragana: 'いた' },
  'いない': { romaji: 'inai', en: 'not there / doesn\'t exist (animate)', hiragana: 'いない' },
  'ある': { romaji: 'aru', en: 'to be / to exist (inanimate)', hiragana: 'ある' },
  'あった': { romaji: 'atta', en: 'was / existed (inanimate, past)', hiragana: 'あった' },
  'ない': { romaji: 'nai', en: 'not / doesn\'t exist', hiragana: 'ない' },
  'なく': { romaji: 'naku', en: 'without / not (te-form of ない)', hiragana: 'なく' },
  'なかった': { romaji: 'nakatta', en: 'did not / was not (past negative)', hiragana: 'なかった' },
  'する': { romaji: 'suru', en: 'to do', hiragana: 'する' },
  'した': { romaji: 'shita', en: 'did (past of する)', hiragana: 'した' },
  'して': { romaji: 'shite', en: 'doing / and then (te-form of する)', hiragana: 'して' },
  'くれる': { romaji: 'kureru', en: 'to give (to me/us)', hiragana: 'くれる' },
  'くれ': { romaji: 'kure', en: 'give me / please do (casual imperative)', hiragana: 'くれ' },
  'なる': { romaji: 'naru', en: 'to become', hiragana: 'なる' },
  'なった': { romaji: 'natta', en: 'became (past of なる)', hiragana: 'なった' },
  'なって': { romaji: 'natte', en: 'becoming (te-form of なる)', hiragana: 'なって' },
  'しまう': { romaji: 'shimau', en: 'to end up doing / unfortunately…', hiragana: 'しまう' },
  'しまった': { romaji: 'shimatta', en: 'ended up doing / oh no! (past)', hiragana: 'しまった' },
  'しまえ': { romaji: 'shimae', en: 'just go ahead and do it! (imperative)', hiragana: 'しまえ' },
  'しまう': { romaji: 'shimau', en: 'to end up (completing something)', hiragana: 'しまう' },
  'てしまった': { romaji: 'te shimatta', en: 'completely did / unfortunately did', hiragana: 'てしまった' },
  'ほしい': { romaji: 'hoshii', en: 'want (someone to do something)', hiragana: 'ほしい' },
  'たい': { romaji: 'tai', en: 'want to do (first person desire)', hiragana: 'たい' },
  'たく': { romaji: 'taku', en: 'want to (negative/conjunctive form)', hiragana: 'たく' },
  'やる': { romaji: 'yaru', en: 'to do / to give (casual)', hiragana: 'やる' },
  'もらう': { romaji: 'morau', en: 'to receive / to have someone do', hiragana: 'もらう' },
  'いく': { romaji: 'iku', en: 'to go', hiragana: 'いく' },
  'いった': { romaji: 'itta', en: 'went (past of いく)', hiragana: 'いった' },
  'くる': { romaji: 'kuru', en: 'to come', hiragana: 'くる' },
  'みる': { romaji: 'miru', en: 'to see / to look / to try doing', hiragana: 'みる' },
  'みせる': { romaji: 'miseru', en: 'to show / to let (someone) see', hiragana: 'みせる' },
  'わかる': { romaji: 'wakaru', en: 'to understand / to know', hiragana: 'わかる' },
  'わかっている': { romaji: 'wakatte iru', en: 'I know / I understand (already)', hiragana: 'わかっている' },
  'できる': { romaji: 'dekiru', en: 'can / to be able to / to be completed', hiragana: 'できる' },
  'できない': { romaji: 'dekinai', en: 'cannot / unable to', hiragana: 'できない' },
  'できなかった': { romaji: 'dekinakatta', en: 'couldn\'t / was unable to', hiragana: 'できなかった' },
  'おもう': { romaji: 'omou', en: 'to think / to feel', hiragana: 'おもう' },
  'いう': { romaji: 'iu', en: 'to say / to call', hiragana: 'いう' },
  'いえる': { romaji: 'ieru', en: 'can say / able to say', hiragana: 'いえる' },
  'いえない': { romaji: 'ienai', en: 'cannot say / can\'t bring myself to say', hiragana: 'いえない' },
  'ねむる': { romaji: 'nemuru', en: 'to sleep', hiragana: 'ねむる' },
  'ねる': { romaji: 'neru', en: 'to sleep / to lie down', hiragana: 'ねる' },
  'わらう': { romaji: 'warau', en: 'to laugh / to smile', hiragana: 'わらう' },
  'わらっちゃう': { romaji: 'waratchau', en: 'find myself laughing (casual)', hiragana: 'わらっちゃう' },
  'わすれる': { romaji: 'wasureru', en: 'to forget', hiragana: 'わすれる' },
  'もとめる': { romaji: 'motomeru', en: 'to seek / desire / want', hiragana: 'もとめる' },
  'きく': { romaji: 'kiku', en: 'to listen / to ask / to hear', hiragana: 'きく' },
  'みつける': { romaji: 'mitsukeru', en: 'to find / discover', hiragana: 'みつける' },
  'さがす': { romaji: 'sagasu', en: 'to search / look for', hiragana: 'さがす' },
  'かえる': { romaji: 'kaeru', en: 'to return / go home', hiragana: 'かえる' },
  'あける': { romaji: 'akeru', en: 'to open', hiragana: 'あける' },
  'とじる': { romaji: 'tojiru', en: 'to close', hiragana: 'とじる' },
  'とじ': { romaji: 'toji', en: 'close / closing (conjunctive)', hiragana: 'とじ' },
  'すう': { romaji: 'suu', en: 'to inhale / suck in', hiragana: 'すう' },
  'よぶ': { romaji: 'yobu', en: 'to call / to invite', hiragana: 'よぶ' },
  'あるく': { romaji: 'aruku', en: 'to walk', hiragana: 'あるく' },
  'ちる': { romaji: 'chiru', en: 'to scatter / fall (petals)', hiragana: 'ちる' },
  'まえる': { romaji: 'maeru', en: 'to give birth / create (芽生える: to bud)', hiragana: 'まえる' },
  'かわく': { romaji: 'kawaku', en: 'to dry / become dry', hiragana: 'かわく' },
  'かたる': { romaji: 'kataru', en: 'to talk / tell / narrate', hiragana: 'かたる' },
  'かたった': { romaji: 'katatta', en: 'talked / narrated (past)', hiragana: 'かたった' },
  'きずつける': { romaji: 'kizutsukeru', en: 'to hurt / wound', hiragana: 'きずつける' },
  'しがみつく': { romaji: 'shigamitsuku', en: 'to cling to / hold on tight', hiragana: 'しがみつく' },
  'たどる': { romaji: 'tadoru', en: 'to trace / follow a path', hiragana: 'たどる' },
  'めぐる': { romaji: 'meguru', en: 'to go around / trace / wander', hiragana: 'めぐる' },
  'かざりつける': { romaji: 'kazaritsukeru', en: 'to decorate / adorn', hiragana: 'かざりつける' },
  'たいせつにする': { romaji: 'taisetsuni suru', en: 'to treasure / take care of', hiragana: 'たいせつにする' },
  'きずく': { romaji: 'kizuku', en: 'to notice / realize', hiragana: 'きずく' },
  'あきらめる': { romaji: 'akirameru', en: 'to give up / accept', hiragana: 'あきらめる' },
  'てばなす': { romaji: 'tebanasu', en: 'to let go of / release', hiragana: 'てばなす' },
  'ひきとめる': { romaji: 'hikitomeru', en: 'to hold back / stop from leaving', hiragana: 'ひきとめる' },
  'つられる': { romaji: 'tsurareru', en: 'to be drawn in / lured by', hiragana: 'つられる' },
  'うかぶ': { romaji: 'ukabu', en: 'to float / come to mind', hiragana: 'うかぶ' },
  'えがく': { romaji: 'egaku', en: 'to draw / picture / depict', hiragana: 'えがく' },
  'よもう': { romaji: 'yomōu', en: 'let\'s read / I\'ll read', hiragana: 'よもう' },
  'もえる': { romaji: 'moeru', en: 'to burn / blaze', hiragana: 'もえる' },
  'そめる': { romaji: 'someru', en: 'to dye / colour / stain', hiragana: 'そめる' },
  'あらわれる': { romaji: 'arawareru', en: 'to appear / show up', hiragana: 'あらわれる' },
  'ねこんで': { romaji: 'netekonde', en: 'lying down / sprawled out', hiragana: 'ねこんで' },
  'のみこむ': { romaji: 'nomikomu', en: 'to swallow / gulp down', hiragana: 'のみこむ' },
  'ふる': { romaji: 'furu', en: 'to fall (rain/snow) / to wave (hand)', hiragana: 'ふる' },
  'こらえる': { romaji: 'koraeru', en: 'to hold back / endure / suppress', hiragana: 'こらえる' },
  'なぐさめる': { romaji: 'nagusameru', en: 'to comfort / console', hiragana: 'なぐさめる' },
  'おぼえる': { romaji: 'oboeru', en: 'to remember / memorize', hiragana: 'おぼえる' },
  'おもいだす': { romaji: 'omoidasu', en: 'to recall / remember', hiragana: 'おもいだす' },
  'すごす': { romaji: 'sugosu', en: 'to spend (time)', hiragana: 'すごす' },
  'あう': { romaji: 'au', en: 'to meet', hiragana: 'あう' },
  'みあげる': { romaji: 'miageru', en: 'to look up at', hiragana: 'みあげる' },
  'てはなす': { romaji: 'tehanasu', en: 'to let go of', hiragana: 'てはなす' },
  'なきながら': { romaji: 'naki nagara', en: 'while crying', hiragana: 'なきながら' },
  'いれば': { romaji: 'ireba', en: 'if (you/they) are here', hiragana: 'いれば' },
  'おわる': { romaji: 'owaru', en: 'to end / finish', hiragana: 'おわる' },
  'おわって': { romaji: 'owatte', en: 'having ended / finishing', hiragana: 'おわって' },

  // ── Common adjectives ─────────────────────────────────────────
  'いい': { romaji: 'ii', en: 'good / fine / okay', hiragana: 'いい' },
  'よい': { romaji: 'yoi', en: 'good (formal)', hiragana: 'よい' },
  'わるい': { romaji: 'warui', en: 'bad / wrong', hiragana: 'わるい' },
  'うつくしい': { romaji: 'utsukushii', en: 'beautiful', hiragana: 'うつくしい' },
  'かなしい': { romaji: 'kanashii', en: 'sad', hiragana: 'かなしい' },
  'うれしい': { romaji: 'ureshii', en: 'happy / glad', hiragana: 'うれしい' },
  'たのしい': { romaji: 'tanoshii', en: 'fun / enjoyable', hiragana: 'たのしい' },
  'つまらない': { romaji: 'tsumaranai', en: 'boring / dull / trivial', hiragana: 'つまらない' },
  'おもしろい': { romaji: 'omoshiroi', en: 'interesting / funny', hiragana: 'おもしろい' },
  'こわい': { romaji: 'kowai', en: 'scary / frightening', hiragana: 'こわい' },
  'いやだ': { romaji: 'iya da', en: 'I hate it / no way / unpleasant', hiragana: 'いやだ' },
  'いや': { romaji: 'iya', en: 'unpleasant / I hate it / no', hiragana: 'いや' },
  'ふあん': { romaji: 'fuan', en: 'anxiety / unease / worry', hiragana: 'ふあん' },
  'とおい': { romaji: 'tōi', en: 'far / distant', hiragana: 'とおい' },
  'ちかい': { romaji: 'chikai', en: 'close / near', hiragana: 'ちかい' },
  'おもい': { romaji: 'omoi', en: 'heavy', hiragana: 'おもい' },
  'むずかしい': { romaji: 'muzukashii', en: 'difficult', hiragana: 'むずかしい' },
  'やさしい': { romaji: 'yasashii', en: 'kind / gentle / easy', hiragana: 'やさしい' },
  'まぶしい': { romaji: 'mabushii', en: 'dazzling / blinding bright', hiragana: 'まぶしい' },
  'たよりない': { romaji: 'tayorinai', en: 'unreliable / helpless', hiragana: 'たよりない' },
  'なつかしい': { romaji: 'natsukashii', en: 'nostalgic / dear old memories', hiragana: 'なつかしい' },
  'あいまい': { romaji: 'aimai', en: 'vague / ambiguous', hiragana: 'あいまい' },
  'わかい': { romaji: 'wakai', en: 'young', hiragana: 'わかい' },
  'ながい': { romaji: 'nagai', en: 'long', hiragana: 'ながい' },
  'むだ': { romaji: 'muda', en: 'pointless / wasteful / in vain', hiragana: 'むだ' },
  'すなお': { romaji: 'sunao', en: 'honest / obedient / straightforward', hiragana: 'すなお' },

  // ── Common nouns ─────────────────────────────────────────────
  'ひと': { romaji: 'hito', en: 'person', hiragana: 'ひと' },
  'きみ': { romaji: 'kimi', en: 'you (casual)', hiragana: 'きみ' },
  'ぼく': { romaji: 'boku', en: 'I / me (masculine, casual)', hiragana: 'ぼく' },
  'わたし': { romaji: 'watashi', en: 'I / me (neutral)', hiragana: 'わたし' },
  'あなた': { romaji: 'anata', en: 'you (neutral/formal)', hiragana: 'あなた' },
  'ひ': { romaji: 'hi', en: 'day / sun / fire', hiragana: 'ひ' },
  'よる': { romaji: 'yoru', en: 'night', hiragana: 'よる' },
  'あさ': { romaji: 'asa', en: 'morning', hiragana: 'あさ' },
  'とき': { romaji: 'toki', en: 'time / moment / when', hiragana: 'とき' },
  'ころ': { romaji: 'koro', en: 'around that time / about', hiragana: 'ころ' },
  'まいにち': { romaji: 'mainichi', en: 'every day', hiragana: 'まいにち' },
  'みらい': { romaji: 'mirai', en: 'future', hiragana: 'みらい' },
  'きのう': { romaji: 'kinō', en: 'yesterday', hiragana: 'きのう' },
  'あした': { romaji: 'ashita', en: 'tomorrow', hiragana: 'あした' },
  'いま': { romaji: 'ima', en: 'now', hiragana: 'いま' },
  'むかし': { romaji: 'mukashi', en: 'the past / long ago', hiragana: 'むかし' },
  'こころ': { romaji: 'kokoro', en: 'heart / mind / spirit', hiragana: 'こころ' },
  'からだ': { romaji: 'karada', en: 'body', hiragana: 'からだ' },
  'かみ': { romaji: 'kami', en: 'hair / god / paper', hiragana: 'かみ' },
  'て': { romaji: 'te', en: 'hand', hiragana: 'て' },
  'め': { romaji: 'me', en: 'eye / bud (芽)', hiragana: 'め' },
  'こえ': { romaji: 'koe', en: 'voice', hiragana: 'こえ' },
  'かお': { romaji: 'kao', en: 'face', hiragana: 'かお' },
  'むね': { romaji: 'mune', en: 'chest / heart', hiragana: 'むね' },
  'うで': { romaji: 'ude', en: 'arm', hiragana: 'うで' },
  'ほし': { romaji: 'hoshi', en: 'star', hiragana: 'ほし' },
  'そら': { romaji: 'sora', en: 'sky', hiragana: 'そら' },
  'みち': { romaji: 'michi', en: 'road / path', hiragana: 'みち' },
  'まち': { romaji: 'machi', en: 'town / city', hiragana: 'まち' },
  'いえ': { romaji: 'ie', en: 'house / home', hiragana: 'いえ' },
  'うた': { romaji: 'uta', en: 'song', hiragana: 'うた' },
  'はな': { romaji: 'hana', en: 'flower / nose', hiragana: 'はな' },
  'いろ': { romaji: 'iro', en: 'colour', hiragana: 'いろ' },
  'ゆめ': { romaji: 'yume', en: 'dream', hiragana: 'ゆめ' },
  'なまえ': { romaji: 'namae', en: 'name', hiragana: 'なまえ' },
  'きおく': { romaji: 'kioku', en: 'memory / recollection', hiragana: 'きおく' },
  'いと': { romaji: 'ito', en: 'thread / string', hiragana: 'いと' },
  'いき': { romaji: 'iki', en: 'breath', hiragana: 'いき' },
  'えいが': { romaji: 'eiga', en: 'movie / film', hiragana: 'えいが' },
  'かんとく': { romaji: 'kantoku', en: 'director (film/sports)', hiragana: 'かんとく' },
  'じんせい': { romaji: 'jinsei', en: 'life / one\'s lifetime', hiragana: 'じんせい' },
  'よゆう': { romaji: 'yoyū', en: 'room / leeway / composure', hiragana: 'よゆう' },
  'くせ': { romaji: 'kuse', en: 'habit / quirk', hiragana: 'くせ' },
  'ため息': { romaji: 'tameiki', en: 'sigh', hiragana: 'ためいき' },
  'ためいき': { romaji: 'tameiki', en: 'sigh', hiragana: 'ためいき' },
  'きず': { romaji: 'kizu', en: 'wound / scratch / scar', hiragana: 'きず' },
  'ぬくもり': { romaji: 'nukumori', en: 'warmth', hiragana: 'ぬくもり' },
  'たから': { romaji: 'takara', en: 'treasure', hiragana: 'たから' },
  'なみだ': { romaji: 'namida', en: 'tears', hiragana: 'なみだ' },
  'さよなら': { romaji: 'sayonara', en: 'goodbye (farewell)', hiragana: 'さよなら' },
  'はな': { romaji: 'hana', en: 'flower / nose', hiragana: 'はな' },
  'さくら': { romaji: 'sakura', en: 'cherry blossom', hiragana: 'さくら' },
  'かれは': { romaji: 'kareha', en: 'dead / fallen leaf', hiragana: 'かれは' },
  'かれ': { romaji: 'kare', en: 'he / him / that (person)', hiragana: 'かれ' },
  'ゆうやけ': { romaji: 'yūyake', en: 'sunset / evening glow', hiragana: 'ゆうやけ' },
  'ゆうぐれ': { romaji: 'yūgure', en: 'dusk / evening', hiragana: 'ゆうぐれ' },
  'はる': { romaji: 'haru', en: 'spring', hiragana: 'はる' },
  'きせつ': { romaji: 'kisetsu', en: 'season', hiragana: 'きせつ' },
  'ほしぞら': { romaji: 'hoshizora', en: 'starry sky', hiragana: 'ほしぞら' },
  'まぼろし': { romaji: 'maboroshi', en: 'illusion / phantom', hiragana: 'まぼろし' },
  'まいにち': { romaji: 'mainichi', en: 'every day', hiragana: 'まいにち' },
  'ひとり': { romaji: 'hitori', en: 'one person / alone', hiragana: 'ひとり' },
  'ふたり': { romaji: 'futari', en: 'two people / the two of us', hiragana: 'ふたり' },
  'みんな': { romaji: 'minna', en: 'everyone / all', hiragana: 'みんな' },
  'だれか': { romaji: 'dareka', en: 'someone / somebody', hiragana: 'だれか' },
  'なにか': { romaji: 'nanika', en: 'something', hiragana: 'なにか' },
  'どこか': { romaji: 'doko ka', en: 'somewhere / some place', hiragana: 'どこか' },
  'どこ': { romaji: 'doko', en: 'where', hiragana: 'どこ' },
  'いつか': { romaji: 'itsuka', en: 'someday / once', hiragana: 'いつか' },
  'なぜ': { romaji: 'naze', en: 'why', hiragana: 'なぜ' },
  'なに': { romaji: 'nani', en: 'what', hiragana: 'なに' },
  'なんで': { romaji: 'nande', en: 'why / what for (casual)', hiragana: 'なんで' },
  'どんな': { romaji: 'donna', en: 'what kind of / what sort', hiragana: 'どんな' },
  'こんな': { romaji: 'konna', en: 'this kind of / like this', hiragana: 'こんな' },
  'そんな': { romaji: 'sonna', en: 'that kind of / like that', hiragana: 'そんな' },
  'あんな': { romaji: 'anna', en: 'that kind of (far away)', hiragana: 'あんな' },
  'この': { romaji: 'kono', en: 'this (before noun)', hiragana: 'この' },
  'その': { romaji: 'sono', en: 'that (before noun)', hiragana: 'その' },
  'あの': { romaji: 'ano', en: 'that (over there / past)', hiragana: 'あの' },
  'ここ': { romaji: 'koko', en: 'here / this place', hiragana: 'ここ' },
  'そこ': { romaji: 'soko', en: 'there / that place', hiragana: 'そこ' },
  'あそこ': { romaji: 'asoko', en: 'over there', hiragana: 'あそこ' },
  'こと': { romaji: 'koto', en: 'thing / matter / fact (abstract)', hiragana: 'こと' },
  'もの': { romaji: 'mono', en: 'thing / object (tangible)', hiragana: 'もの' },
  'とき': { romaji: 'toki', en: 'time / when / moment', hiragana: 'とき' },
  'ため': { romaji: 'tame', en: 'for / sake of / in order to', hiragana: 'ため' },
  'まま': { romaji: 'mama', en: 'as it is / remaining / still', hiragana: 'まま' },
  'ほう': { romaji: 'hō', en: 'direction / way / alternative', hiragana: 'ほう' },
  'なか': { romaji: 'naka', en: 'inside / middle / among', hiragana: 'なか' },
  'うえ': { romaji: 'ue', en: 'above / top / up', hiragana: 'うえ' },
  'した': { romaji: 'shita', en: 'below / under / beneath', hiragana: 'した' },
  'まえ': { romaji: 'mae', en: 'in front / before / ago', hiragana: 'まえ' },
  'うしろ': { romaji: 'ushiro', en: 'behind / back', hiragana: 'うしろ' },
  'となり': { romaji: 'tonari', en: 'next to / beside', hiragana: 'となり' },
  'そば': { romaji: 'soba', en: 'beside / nearby', hiragana: 'そば' },

  // ── Common adverbs & expressions ──────────────────────────────
  'ずっと': { romaji: 'zutto', en: 'all along / always / continuously', hiragana: 'ずっと' },
  'もっと': { romaji: 'motto', en: 'more / even more', hiragana: 'もっと' },
  'また': { romaji: 'mata', en: 'again / also / and', hiragana: 'また' },
  'もう': { romaji: 'mō', en: 'already / anymore / soon', hiragana: 'もう' },
  'まだ': { romaji: 'mada', en: 'still / not yet', hiragana: 'まだ' },
  'いつも': { romaji: 'itsumo', en: 'always / usually', hiragana: 'いつも' },
  'ゆっくり': { romaji: 'yukkuri', en: 'slowly / take your time', hiragana: 'ゆっくり' },
  'やっと': { romaji: 'yatto', en: 'finally / at last', hiragana: 'やっと' },
  'ぜんぜん': { romaji: 'zenzen', en: 'not at all / totally (colloquial)', hiragana: 'ぜんぜん' },
  'ぜんぶ': { romaji: 'zenbu', en: 'all / everything / the whole', hiragana: 'ぜんぶ' },
  'すべて': { romaji: 'subete', en: 'all / everything', hiragana: 'すべて' },
  'とても': { romaji: 'totemo', en: 'very / extremely', hiragana: 'とても' },
  'なんだか': { romaji: 'nandaka', en: 'somehow / for some reason', hiragana: 'なんだか' },
  'どんどん': { romaji: 'dondon', en: 'rapidly / one after another', hiragana: 'どんどん' },
  'ただ': { romaji: 'tada', en: 'just / simply / merely', hiragana: 'ただ' },
  'ただし': { romaji: 'tadashi', en: 'however / but / provided that', hiragana: 'ただし' },
  'たぶん': { romaji: 'tabun', en: 'probably / perhaps', hiragana: 'たぶん' },
  'きっと': { romaji: 'kitto', en: 'surely / certainly / I bet', hiragana: 'きっと' },
  'もちろん': { romaji: 'mochiron', en: 'of course / certainly', hiragana: 'もちろん' },
  'やはり': { romaji: 'yahari', en: 'as expected / after all', hiragana: 'やはり' },
  'やっぱり': { romaji: 'yappari', en: 'as I thought / after all (casual)', hiragana: 'やっぱり' },
  'でも': { romaji: 'demo', en: 'but / however / even so', hiragana: 'でも' },
  'しかし': { romaji: 'shikashi', en: 'however / but (formal)', hiragana: 'しかし' },
  'ねえ': { romaji: 'nee', en: 'hey / come on (casual address)', hiragana: 'ねえ' },
  'あの': { romaji: 'ano', en: 'um… / that (distant)', hiragana: 'あの' },
  'えっと': { romaji: 'etto', en: 'um… / let me think', hiragana: 'えっと' },
  'ほら': { romaji: 'hora', en: 'look! / there! / see?', hiragana: 'ほら' },
  'ありがとう': { romaji: 'arigatō', en: 'thank you', hiragana: 'ありがとう' },
  'ごめん': { romaji: 'gomen', en: 'sorry / excuse me', hiragana: 'ごめん' },
  'うそ': { romaji: 'uso', en: 'lie / no way! / really?', hiragana: 'うそ' },
  'ほんとう': { romaji: 'hontō', en: 'truth / really / truly', hiragana: 'ほんとう' },
  'だいじょうぶ': { romaji: 'daijōbu', en: 'it\'s okay / don\'t worry / alright', hiragana: 'だいじょうぶ' },

  // ── Song-specific words not elsewhere ─────────────────────────
  '遊園地': { romaji: 'yūenchi', en: 'amusement park', hiragana: 'ゆうえんち' },
  'アスファルト': { romaji: 'asufanto', en: 'asphalt / pavement', hiragana: 'アスファルト' },
  '明け方': { romaji: 'akegata', en: 'dawn / just before sunrise', hiragana: 'あけがた' },
  '枯れ葉': { romaji: 'kareha', en: 'dead / fallen leaf', hiragana: 'かれは' },
  '桜': { romaji: 'sakura', en: 'cherry blossom', hiragana: 'さくら' },
  '芽生える': { romaji: 'mabae ru', en: 'to bud / sprout / be born', hiragana: 'めばえる' },
  '監督': { romaji: 'kantoku', en: 'director (film/sports)', hiragana: 'かんとく' },
  '悪戯': { romaji: 'itazura', en: 'mischief / prank / naughty', hiragana: 'いたずら' },
  '嘘つき': { romaji: 'usotsuki', en: 'liar / someone who lies', hiragana: 'うそつき' },
  '曖昧': { romaji: 'aimai', en: 'vague / ambiguous', hiragana: 'あいまい' },
  '想像': { romaji: 'sōzō', en: 'imagination / to imagine', hiragana: 'そうぞう' },
  '永遠': { romaji: 'eien', en: 'eternity / forever', hiragana: 'えいえん' },
  '果て': { romaji: 'hate', en: 'end / limit / extremity', hiragana: 'はて' },
  '懐かしい': { romaji: 'natsukashii', en: 'nostalgic / dear old memory', hiragana: 'なつかしい' },
  '納得': { romaji: 'nattoku', en: 'understanding / being convinced', hiragana: 'なっとく' },
  '全力': { romaji: 'zenryoku', en: 'full effort / all-out', hiragana: 'ぜんりょく' },
  '全身': { romaji: 'zenshin', en: 'whole body / entire self', hiragana: 'ぜんしん' },
  '矛盾': { romaji: 'mujun', en: 'contradiction / inconsistency', hiragana: 'むじゅん' },
  '無茶苦茶': { romaji: 'muchakucha', en: 'chaotic / absurd / outrageous', hiragana: 'むちゃくちゃ' },
  '気だるさ': { romaji: 'kidarusa', en: 'sluggishness / listlessness', hiragana: 'きだるさ' },
  '喧嘩': { romaji: 'kenka', en: 'fight / quarrel / argument', hiragana: 'けんか' },
  '幻': { romaji: 'maboroshi', en: 'illusion / phantom / vision', hiragana: 'まぼろし' },
  '馬鹿': { romaji: 'baka', en: 'fool / idiot / stupid', hiragana: 'ばか' },
  '馬鹿馬鹿しい': { romaji: 'bakabakashii', en: 'ridiculous / absurd / foolish', hiragana: 'ばかばかしい' },
  '腕': { romaji: 'ude', en: 'arm', hiragana: 'うで' },
  '傷': { romaji: 'kizu', en: 'wound / scar', hiragana: 'きず' },
  '捨て猫': { romaji: 'suteneko', en: 'stray cat / abandoned cat', hiragana: 'すてねこ' },
  '精一杯': { romaji: 'seiippai', en: 'with all one\'s might / as best as one can', hiragana: 'せいいっぱい' },
  '宝物': { romaji: 'takaramono', en: 'treasure / precious thing', hiragana: 'たからもの' },
  '若すぎる': { romaji: 'wakasugiru', en: 'too young', hiragana: 'わかすぎる' },
  '頼りない': { romaji: 'tayorinai', en: 'unreliable / helpless', hiragana: 'たよりない' },
  '身体': { romaji: 'karada', en: 'body', hiragana: 'からだ' },
  '諦め': { romaji: 'akirame', en: 'resignation / giving up', hiragana: 'あきらめ' },
  '温もり': { romaji: 'nukumori', en: 'warmth', hiragana: 'ぬくもり' },
  '人生': { romaji: 'jinsei', en: 'life / one\'s lifetime', hiragana: 'じんせい' },
  '自分': { romaji: 'jibun', en: 'oneself / myself / yourself', hiragana: 'じぶん' },
  '昨日': { romaji: 'kinō', en: 'yesterday', hiragana: 'きのう' },
  '明日': { romaji: 'ashita', en: 'tomorrow', hiragana: 'あした' },
  '記憶': { romaji: 'kioku', en: 'memory', hiragana: 'きおく' },
  '未来': { romaji: 'mirai', en: 'future', hiragana: 'みらい' },
  '星': { romaji: 'hoshi', en: 'star', hiragana: 'ほし' },
  '道': { romaji: 'michi', en: 'road / path', hiragana: 'みち' },
  '夜': { romaji: 'yoru', en: 'night', hiragana: 'よる' },
  '窓': { romaji: 'mado', en: 'window', hiragana: 'まど' },
  '笑顔': { romaji: 'egao', en: 'smiling face / smile', hiragana: 'えがお' },
  '幸せ': { romaji: 'shiawase', en: 'happiness / happy', hiragana: 'しあわせ' },
  '願い': { romaji: 'negai', en: 'wish / hope / prayer', hiragana: 'ねがい' },
  '想い出': { romaji: 'omoide', en: 'memory / memories', hiragana: 'おもいで' },
  '思い出': { romaji: 'omoide', en: 'memory / memories', hiragana: 'おもいで' },
  '気持ち': { romaji: 'kimochi', en: 'feeling / emotion', hiragana: 'きもち' },
  '彼女': { romaji: 'kanojo', en: 'girlfriend / she / her', hiragana: 'かのじょ' },
  '日々': { romaji: 'hibi', en: 'days / daily life', hiragana: 'ひび' },
  '毎日': { romaji: 'mainichi', en: 'every day', hiragana: 'まいにち' },
  '時間': { romaji: 'jikan', en: 'time', hiragana: 'じかん' },
  '一緒': { romaji: 'issho', en: 'together', hiragana: 'いっしょ' },
  '世界': { romaji: 'sekai', en: 'world', hiragana: 'せかい' },
  '光': { romaji: 'hikari', en: 'light', hiragana: 'ひかり' },
  '愛': { romaji: 'ai', en: 'love', hiragana: 'あい' },
  '恋': { romaji: 'koi', en: 'romantic love / being in love', hiragana: 'こい' },
  '春': { romaji: 'haru', en: 'spring', hiragana: 'はる' },
  '涙': { romaji: 'namida', en: 'tears', hiragana: 'なみだ' },
  '心': { romaji: 'kokoro', en: 'heart / mind', hiragana: 'こころ' },
  '夢': { romaji: 'yume', en: 'dream', hiragana: 'ゆめ' },
  '痛み': { romaji: 'itami', en: 'pain', hiragana: 'いたみ' },
  '雨': { romaji: 'ame', en: 'rain', hiragana: 'あめ' },
  '風': { romaji: 'kaze', en: 'wind', hiragana: 'かぜ' },
  '空': { romaji: 'sora', en: 'sky', hiragana: 'そら' },
  '髪': { romaji: 'kami', en: 'hair', hiragana: 'かみ' },
  '愛': { romaji: 'ai', en: 'love', hiragana: 'あい' },
  '声': { romaji: 'koe', en: 'voice', hiragana: 'こえ' },
  '猫': { romaji: 'neko', en: 'cat', hiragana: 'ねこ' },
  '歌': { romaji: 'uta', en: 'song', hiragana: 'うた' },
  '花': { romaji: 'hana', en: 'flower', hiragana: 'はな' },
  '街': { romaji: 'machi', en: 'town / city / neighbourhood', hiragana: 'まち' },
  '今': { romaji: 'ima', en: 'now', hiragana: 'いま' },
  '人': { romaji: 'hito', en: 'person', hiragana: 'ひと' },
  '別': { romaji: 'betsu', en: 'separate / different / another', hiragana: 'べつ' },
  '二人': { romaji: 'futari', en: 'two people / the two of us', hiragana: 'ふたり' },
  '一番': { romaji: 'ichiban', en: 'number one / the most', hiragana: 'いちばん' },
  '隣': { romaji: 'tonari', en: 'next to / the one beside', hiragana: 'となり' },
  '何気ない': { romaji: 'nanigenai', en: 'casual / ordinary / natural', hiragana: 'なにげない' },

  // ── Single kanji — each one is a core morpheme with meaning ─────
  '僕': { romaji: 'boku', en: 'I / me (masculine, casual)', hiragana: 'ぼく', example: '僕は音楽が好きだ', exampleEn: 'I love music' },
  '私': { romaji: 'watashi', en: 'I / me (neutral)', hiragana: 'わたし', example: '私の夢は歌手だ', exampleEn: 'My dream is to be a singer' },
  '君': { romaji: 'kimi', en: 'you (casual / intimate)', hiragana: 'きみ', example: '君が好きだ', exampleEn: 'I like you' },
  '誰': { romaji: 'dare', en: 'who', hiragana: 'だれ', example: '誰ですか？', exampleEn: 'Who is it?' },
  '大': { romaji: 'ō / dai', en: 'big / great / very', hiragana: 'おお', example: '大きな夢を持つ', exampleEn: 'Have big dreams' },
  '外': { romaji: 'soto', en: 'outside / beyond', hiragana: 'そと', example: '外は寒い', exampleEn: 'It\'s cold outside' },
  '前': { romaji: 'mae', en: 'before / in front / ago', hiragana: 'まえ', example: '前に進もう', exampleEn: 'Let\'s move forward' },
  '後': { romaji: 'ato / go', en: 'after / later / behind', hiragana: 'あと', example: '後で話そう', exampleEn: 'Let\'s talk later' },
  '長': { romaji: 'naga', en: 'long (root form)', hiragana: 'なが', example: '長い夜が続く', exampleEn: 'Long nights continue' },
  '強': { romaji: 'tsuyoi', en: 'strong', hiragana: 'つよい', example: '強い風が吹く', exampleEn: 'A strong wind blows' },
  '変': { romaji: 'hen / kawaru', en: 'strange / change', hiragana: 'へん', example: '変な夢を見た', exampleEn: 'I had a strange dream' },
  '夏': { romaji: 'natsu', en: 'summer', hiragana: 'なつ', example: '夏の午後', exampleEn: 'A summer afternoon' },
  '白': { romaji: 'shiro', en: 'white', hiragana: 'しろ', example: '白い息が見える', exampleEn: 'You can see white breath' },
  '色': { romaji: 'iro', en: 'colour', hiragana: 'いろ', example: '君色に染まる', exampleEn: 'Dyed in your colour' },
  '生': { romaji: 'sei / i', en: 'life / live', hiragana: 'せい', example: '生きていることに感謝', exampleEn: 'Grateful to be alive' },
  '同': { romaji: 'onaji / dō', en: 'same / identical', hiragana: 'おなじ', example: '同じ空の下', exampleEn: 'Under the same sky' },
  '名': { romaji: 'na / mei', en: 'name', hiragana: 'な', example: '名前を呼ぶ', exampleEn: 'Call someone\'s name' },
  '早': { romaji: 'haya', en: 'early / fast / soon', hiragana: 'はや', example: '早く会いたい', exampleEn: 'I want to see you soon' },
  '全': { romaji: 'subete / zen', en: 'all / everything / whole', hiragana: 'ぜん', example: '全てを話した', exampleEn: 'Told everything' },
  '重': { romaji: 'omoi / jū', en: 'heavy / important', hiragana: 'おもい', example: 'この言葉は重い', exampleEn: 'These words carry weight' },
  '会': { romaji: 'au / kai', en: 'meet / assembly', hiragana: 'あう', example: 'また会いたい', exampleEn: 'I want to meet again' },
  '出': { romaji: 'deru / de', en: 'exit / come out / produce', hiragana: 'でる', example: '外に出よう', exampleEn: 'Let\'s go outside' },
  '分': { romaji: 'wakaru / fun', en: 'understand / part / minute', hiragana: 'わかる', example: '気持ちが分かる', exampleEn: 'I understand how you feel' },
  '聞': { romaji: 'kiku', en: 'listen / hear / ask', hiragana: 'きく', example: '音楽を聞く', exampleEn: 'Listen to music' },
  '終': { romaji: 'owaru', en: 'end / finish', hiragana: 'おわる', example: '夢が終わる', exampleEn: 'The dream ends' },
  '泣': { romaji: 'naku', en: 'cry / weep', hiragana: 'なく', example: '泣かないで', exampleEn: 'Don\'t cry' },
  '笑': { romaji: 'warau', en: 'laugh / smile', hiragana: 'わらう', example: '笑顔を見せて', exampleEn: 'Show me your smile' },
  '眠': { romaji: 'nemuru', en: 'sleep / slumber', hiragana: 'ねむる', example: 'ゆっくり眠ってね', exampleEn: 'Sleep well' },
  '歩': { romaji: 'aruku', en: 'walk', hiragana: 'あるく', example: '二人で歩く', exampleEn: 'Walk together' },
  '引': { romaji: 'hiku', en: 'pull / attract', hiragana: 'ひく', example: '手を引く', exampleEn: 'Pull someone\'s hand' },
  '散': { romaji: 'chiru', en: 'scatter / fall (petals)', hiragana: 'ちる', example: '桜が散る', exampleEn: 'Cherry blossoms scatter' },
  '染': { romaji: 'someru', en: 'dye / colour / tint', hiragana: 'そめる', example: '空を染める夕焼け', exampleEn: 'Sunset that dyes the sky' },
  '止': { romaji: 'tomeru / tomu', en: 'stop / cease', hiragana: 'とまる', example: '涙が止まらない', exampleEn: 'The tears won\'t stop' },
  '探': { romaji: 'sagasu', en: 'search / look for', hiragana: 'さがす', example: '答えを探している', exampleEn: 'Searching for the answer' },
  '開': { romaji: 'akeru', en: 'open', hiragana: 'あける', example: '窓を開けよう', exampleEn: 'Let\'s open the window' },
  '閉': { romaji: 'tojiru', en: 'close / shut', hiragana: 'とじる', example: '目を閉じて', exampleEn: 'Close your eyes' },
  '降': { romaji: 'furu', en: 'fall / come down (rain/snow)', hiragana: 'ふる', example: '雨が降る', exampleEn: 'Rain falls' },
  '離': { romaji: 'hanareru', en: 'separate / move apart', hiragana: 'はなれる', example: '遠く離れても', exampleEn: 'Even if we are far apart' },
  '通': { romaji: 'tōru', en: 'pass through / go along', hiragana: 'とおる', example: 'この道を通る', exampleEn: 'Pass along this road' },
  '切': { romaji: 'kiru', en: 'cut / sever', hiragana: 'きる', example: '関係を切る', exampleEn: 'Sever ties' },
  '合': { romaji: 'au', en: 'fit / suit / combine / each other', hiragana: 'あう', example: '気が合う', exampleEn: 'We get along / click' },
  '逢': { romaji: 'au', en: 'meet (literary / emotional)', hiragana: 'あう', example: 'いつか逢える', exampleEn: 'We\'ll meet again someday' },
  '明': { romaji: 'akeru / mei', en: 'brighten / dawn / bright', hiragana: 'あける', example: '夜が明ける', exampleEn: 'Dawn breaks' },
  '乾': { romaji: 'kawaku', en: 'dry', hiragana: 'かわく', example: '髪が乾く', exampleEn: 'Hair dries' },
  '付': { romaji: 'tsuku', en: 'attach / notice / light up', hiragana: 'つく', example: '気が付く', exampleEn: 'Notice / become aware' },
  '飲': { romaji: 'nomu', en: 'drink / swallow', hiragana: 'のむ', example: 'お茶を飲む', exampleEn: 'Drink tea' },
  '揺': { romaji: 'yureru', en: 'sway / shake / tremble', hiragana: 'ゆれる', example: '風に揺れる', exampleEn: 'Sway in the wind' },
  '舞': { romaji: 'mau', en: 'dance / flutter', hiragana: 'まう', example: '雪が舞う', exampleEn: 'Snow dances in the air' },
  '求': { romaji: 'motomeru', en: 'seek / desire / request', hiragana: 'もとめる', example: '愛を求める', exampleEn: 'Seek love' },
  '呼': { romaji: 'yobu', en: 'call / summon', hiragana: 'よぶ', example: '名前を呼び合う', exampleEn: 'Call each other\'s names' },
  '吸': { romaji: 'suu', en: 'inhale / breathe in', hiragana: 'すう', example: '息を吸う', exampleEn: 'Take a breath' },
  '吹': { romaji: 'fuku', en: 'blow (wind)', hiragana: 'ふく', example: '風が吹く', exampleEn: 'The wind blows' },
  '芽': { romaji: 'me', en: 'bud / sprout', hiragana: 'め', example: '芽が出る', exampleEn: 'A bud sprouts' },
  '渡': { romaji: 'wataru', en: 'cross / go across', hiragana: 'わたる', example: '橋を渡る', exampleEn: 'Cross a bridge' },
  '濡': { romaji: 'nureru', en: 'get wet', hiragana: 'ぬれる', example: '雨に濡れる', exampleEn: 'Get wet in the rain' },
  '寝': { romaji: 'neru', en: 'sleep / lie down', hiragana: 'ねる', example: '早く寝て', exampleEn: 'Go to sleep' },
  '居': { romaji: 'iru', en: 'be / exist (animate)', hiragana: 'いる', example: 'ここに居る', exampleEn: 'I\'m right here' },
  '巡': { romaji: 'meguru', en: 'go around / wander through', hiragana: 'めぐる', example: '記憶を巡る', exampleEn: 'Wander through memories' },
  '辿': { romaji: 'tadoru', en: 'trace / follow a path', hiragana: 'たどる', example: '記憶の糸を辿る', exampleEn: 'Trace the thread of memory' },
  '落': { romaji: 'ochiru', en: 'fall / drop', hiragana: 'おちる', example: '涙が落ちる', exampleEn: 'Tears fall' },
  '過': { romaji: 'sugiru', en: 'pass / go by / too much', hiragana: 'すぎる', example: '時が過ぎる', exampleEn: 'Time passes' },
  '転': { romaji: 'korogaru', en: 'roll / tumble / fall over', hiragana: 'ころがる', example: '転んでも立ち上がる', exampleEn: 'Even if you fall, get up' },
  '描': { romaji: 'egaku', en: 'draw / picture / depict', hiragana: 'えがく', example: '夢を描く', exampleEn: 'Paint a dream' },
  '現': { romaji: 'arawaru', en: 'appear / present', hiragana: 'あらわれる', example: '姿を現す', exampleEn: 'Appear / show oneself' },
  '面': { romaji: 'omote / tsura', en: 'face / surface / side', hiragana: 'おもて', example: '正面から向き合う', exampleEn: 'Face head-on' },
  '頃': { romaji: 'koro', en: 'around that time / about', hiragana: 'ごろ', example: '夕方頃に来て', exampleEn: 'Come around evening' },
  '好': { romaji: 'suki', en: 'like / fond of (root)', hiragana: 'すき', example: '大好きな人', exampleEn: 'A person I really love' },
  '嫌': { romaji: 'iya', en: 'dislike / unpleasant / no way', hiragana: 'いや', example: '嫌いじゃない', exampleEn: 'I don\'t dislike it' },
  '安': { romaji: 'yasu / an', en: 'cheap / ease / relief / peace', hiragana: 'やすい', example: '安心した', exampleEn: 'Feeling relieved' },
  '怒': { romaji: 'okoru', en: 'get angry', hiragana: 'おこる', example: '怒らないで', exampleEn: 'Don\'t be angry' },
  '怖': { romaji: 'kowai', en: 'scary / frightening', hiragana: 'こわい', example: '怖い夢を見た', exampleEn: 'Had a scary dream' },
  '思': { romaji: 'omou', en: 'think / feel / consider', hiragana: 'おもう', example: 'あなたのことを思う', exampleEn: 'I think of you' },
  '手': { romaji: 'te', en: 'hand', hiragana: 'て', example: '手を繋ごう', exampleEn: 'Let\'s hold hands' },
  '抱': { romaji: 'daku', en: 'hold / embrace / hug', hiragana: 'だく', example: 'ぎゅっと抱きしめる', exampleEn: 'Hold tightly' },
  '拭': { romaji: 'nugu / fuku', en: 'wipe / wipe away', hiragana: 'ぬぐう', example: '傷を拭う', exampleEn: 'Wipe a wound clean' },
  '見': { romaji: 'miru', en: 'see / look / watch', hiragana: 'みる', example: '星を見ていた', exampleEn: 'Was watching the stars' },
  '言': { romaji: 'iu', en: 'say / speak / tell', hiragana: 'いう', example: '何も言えない', exampleEn: 'Can\'t say anything' },
  '気': { romaji: 'ki', en: 'feeling / spirit / mood', hiragana: 'き', example: '気持ちが大事', exampleEn: 'Feelings are important' },
  '目': { romaji: 'me', en: 'eye', hiragana: 'め', example: '目が離せない', exampleEn: 'Can\'t take my eyes off' },
  '足': { romaji: 'ashi / tari', en: 'foot / leg / enough', hiragana: 'あし', example: '足が痛い', exampleEn: 'My feet hurt' },
  '日': { romaji: 'hi / nichi', en: 'day / sun', hiragana: 'ひ', example: 'あの日のことを覚えてる', exampleEn: 'I remember that day' },
  '時': { romaji: 'toki', en: 'time / moment / when', hiragana: 'とき', example: '辛い時もある', exampleEn: 'There are also tough times' },
  '方': { romaji: 'hō / kata', en: 'direction / way / person (polite)', hiragana: 'ほう', example: 'どちらの方ですか？', exampleEn: 'Which way / which person?' },
  '行': { romaji: 'iku / yuku', en: 'go', hiragana: 'いく', example: 'どこに行くの？', exampleEn: 'Where are you going?' },
  '来': { romaji: 'kuru / ki', en: 'come', hiragana: 'くる', example: 'また来てね', exampleEn: 'Come again' },
  '色': { romaji: 'iro', en: 'colour', hiragana: 'いろ', example: '君色に染めて', exampleEn: 'Dye it in your colour' },
  '遠': { romaji: 'tōi / tōku', en: 'far / distant', hiragana: 'とおい', example: '遠くから聞こえる', exampleEn: 'Can be heard from far away' },
  '未': { romaji: 'mada / mi', en: 'not yet / un- (prefix)', hiragana: 'まだ', example: '未来はまだ分からない', exampleEn: 'The future is still unknown' },
  '事': { romaji: 'koto', en: 'thing / matter / fact (abstract)', hiragana: 'こと', example: '好きな事をしよう', exampleEn: 'Let\'s do the things we love' },
  '切': { romaji: 'kiru / kirenai', en: 'cut / cannot stop doing', hiragana: 'きる', example: '忘れ切れない', exampleEn: 'Can\'t completely forget' },
  '部': { romaji: 'bu / hen', en: 'part / section / department', hiragana: 'ぶ', example: '身体の一部', exampleEn: 'A part of the body' },
  '能': { romaji: 'nō', en: 'ability / can', hiragana: 'のう', example: '可能な限り', exampleEn: 'As much as possible' },
  '可': { romaji: 'ka / yoi', en: 'possible / allowed / passable', hiragana: 'か', example: '可能性がある', exampleEn: 'There is possibility' },
  '冷': { romaji: 'hieru / tsumeta', en: 'cold / cool / chill', hiragana: 'ひえる', example: '夜は冷えた', exampleEn: 'The night grew cold' },
  '度': { romaji: 'do / tabi', en: 'degree / time / occasion', hiragana: 'ど', example: '何度も繰り返す', exampleEn: 'Repeat many times' },
  '並': { romaji: 'narabu', en: 'line up / row / average', hiragana: 'ならぶ', example: '星が並ぶ', exampleEn: 'Stars line up' },
  '以': { romaji: 'i', en: 'by means of / compared to / since', hiragana: 'い', example: '以前より上手になった', exampleEn: 'Got better than before' },
  '込': { romaji: 'komu', en: 'go into /込 (intensifier)', hiragana: 'こむ', example: '飲み込む', exampleEn: 'Swallow / gulp down' },
  '詳': { romaji: 'kuwashii', en: 'detailed / knowledgeable about', hiragana: 'くわしい', example: '詳しく教えて', exampleEn: 'Please explain in detail' },
  '語': { romaji: 'kataru', en: 'tell / speak / language', hiragana: 'かたる', example: '夢を語る', exampleEn: 'Talk about one\'s dreams' },
  '愚': { romaji: 'gu', en: 'foolish (in 愚痴 = complaint)', hiragana: 'ぐ', example: '愚痴を言う', exampleEn: 'Complain / vent' },
  '鮮': { romaji: 'azayaka / sen', en: 'vivid / fresh / brilliant', hiragana: 'あざやか', example: '鮮明に覚えている', exampleEn: 'Remember vividly' },
  '鳴': { romaji: 'naru / naku', en: 'sound / ring / cry (animal)', hiragana: 'なる', example: '鈴が鳴る', exampleEn: 'A bell rings' },
  '駄': { romaji: 'da', en: 'no good / poor (in 無駄 = waste)', hiragana: 'だ', example: '無駄にしない', exampleEn: 'Won\'t waste it' },
  '叱': { romaji: 'shikaru', en: 'scold / tell off', hiragana: 'しかる', example: '先生に叱られた', exampleEn: 'Got told off by the teacher' },
  '数': { romaji: 'kazoeru / kazu', en: 'count / number', hiragana: 'かぞえる', example: '星を数えた', exampleEn: 'Counted the stars' },
  '痴': { romaji: 'chi', en: 'foolish (in 愚痴 = grumbling)', hiragana: 'ち', example: '愚痴をこぼす', exampleEn: 'Spill out complaints' },
  '遺': { romaji: 'nokoru / i', en: 'leave behind / bequest', hiragana: 'のこる', example: '遺した言葉', exampleEn: 'Words left behind' },

  // ── Compound words from lyrics not yet covered ─────────────────
  '飲み込む': { romaji: 'nomikomu', en: 'swallow / gulp down', hiragana: 'のみこむ', example: '息を飲み込む', exampleEn: 'Swallow one\'s breath' },
  '飲み込んで': { romaji: 'nomikonde', en: 'swallowing (te-form)', hiragana: 'のみこんで', example: '全てを飲み込んで', exampleEn: 'Swallowing everything up' },
  '手放す': { romaji: 'tebanasu', en: 'let go of / release', hiragana: 'てばなす', example: '夢を手放したくない', exampleEn: 'I don\'t want to let go of my dreams' },
  '手放し': { romaji: 'tebanashi', en: 'letting go (stem)', hiragana: 'てばなし', example: '手放しで喜ぶ', exampleEn: 'Rejoice without reservation' },
  '寝転ぶ': { romaji: 'nekorobu', en: 'lie down / sprawl out', hiragana: 'ねころぶ', example: 'ソファに寝転ぶ', exampleEn: 'Lie down on the sofa' },
  '寝転んで': { romaji: 'nekokonde', en: 'lying down (te-form)', hiragana: 'ねころんで', example: '床に寝転んでいる', exampleEn: 'Lying sprawled on the floor' },
  '通り過ぎる': { romaji: 'tōrisugiru', en: 'pass by / go past', hiragana: 'とおりすぎる', example: '時間が通り過ぎた', exampleEn: 'Time passed by' },
  '通り過ぎた': { romaji: 'tōrisugita', en: 'passed by (past tense)', hiragana: 'とおりすぎた', example: 'バスが通り過ぎた', exampleEn: 'The bus went past' },
  'どうしようもない': { romaji: 'dōshiyō mo nai', en: 'can\'t be helped / hopeless / overwhelming', hiragana: 'どうしようもない', example: 'どうしようもない気持ち', exampleEn: 'An overwhelming feeling' },
  '見渡す': { romaji: 'miwatasu', en: 'look around / survey', hiragana: 'みわたす', example: 'あたりを見渡す', exampleEn: 'Look around the area' },
  '見渡して': { romaji: 'miwatashite', en: 'looking around (te-form)', hiragana: 'みわたして', example: 'どこを見渡しても', exampleEn: 'No matter where I look' },
  '怒鳴る': { romaji: 'donaru', en: 'shout / yell', hiragana: 'どなる', example: '大声で怒鳴る', exampleEn: 'Shout at the top of one\'s voice' },
  '大はしゃぎ': { romaji: 'ōhashagi', en: 'going wild / getting rowdy / making a big fuss', hiragana: 'おおはしゃぎ', example: '子供が大はしゃぎ', exampleEn: 'Kids going wild' },
  'さらける': { romaji: 'sarakeru', en: 'expose / lay bare', hiragana: 'さらける', example: '全てをさらけ出す', exampleEn: 'Expose everything / bare one\'s soul' },
  'さらけ出す': { romaji: 'sarakedasu', en: 'expose oneself / bare one\'s soul', hiragana: 'さらけだす', example: '気持ちをさらけ出す', exampleEn: 'Lay one\'s feelings bare' },
  '旅立つ': { romaji: 'tabidatsu', en: 'set out on a journey / depart', hiragana: 'たびだつ', example: '旅立ちの朝', exampleEn: 'The morning of departure' },
  '旅立って': { romaji: 'tabidatte', en: 'setting off (te-form)', hiragana: 'たびだって', example: '君は旅立ってしまった', exampleEn: 'You went and set off' },
  '詳しい': { romaji: 'kuwashii', en: 'knowledgeable / detailed / well-versed', hiragana: 'くわしい', example: '音楽に詳しい', exampleEn: 'Knowledgeable about music' },
  '鮮明': { romaji: 'senmei', en: 'vivid / clear / sharp', hiragana: 'せんめい', example: '鮮明に覚えている', exampleEn: 'Remember vividly' },
  '不安': { romaji: 'fuan', en: 'anxiety / unease / worry', hiragana: 'ふあん', example: '不安で眠れない', exampleEn: 'Too anxious to sleep' },
  '愚痴': { romaji: 'guchi', en: 'complaint / grumbling', hiragana: 'ぐち', example: '愚痴を言う', exampleEn: 'Complain / grumble' },
  '尊敬': { romaji: 'sonkei', en: 'respect / admiration', hiragana: 'そんけい', example: '尊敬できる人', exampleEn: 'A person worthy of respect' },
  '態度': { romaji: 'taido', en: 'attitude / manner', hiragana: 'たいど', example: '態度が大切だ', exampleEn: 'Attitude matters' },
  '現実': { romaji: 'genjitsu', en: 'reality / the real world', hiragana: 'げんじつ', example: '現実を見つめる', exampleEn: 'Face reality' },
  '希望': { romaji: 'kibō', en: 'hope / wish / aspiration', hiragana: 'きぼう', example: '希望を持ち続ける', exampleEn: 'Keep holding onto hope' },
  '喧嘩': { romaji: 'kenka', en: 'fight / quarrel', hiragana: 'けんか', example: '喧嘩したくない', exampleEn: 'I don\'t want to fight' },
  '口喧嘩': { romaji: 'kuchigenka', en: 'verbal argument / quarrel', hiragana: 'くちげんか', example: '口喧嘩にならない', exampleEn: 'Doesn\'t turn into an argument' },
  '言葉': { romaji: 'kotoba', en: 'word / words / language', hiragana: 'ことば', example: '言葉が出ない', exampleEn: 'No words come out' },
  '一生懸命': { romaji: 'isshōkenmei', en: 'with all one\'s effort / as hard as one can', hiragana: 'いっしょうけんめい', example: '一生懸命頑張る', exampleEn: 'Try one\'s absolute hardest' },
  '余裕': { romaji: 'yoyū', en: 'composure / leeway / room', hiragana: 'よゆう', example: '余裕を持って', exampleEn: 'With composure / taking it easy' },
  'おとなしい': { romaji: 'otonashii', en: 'quiet / well-behaved / gentle', hiragana: 'おとなしい', example: 'おとなしくしてる', exampleEn: 'Staying quiet / being well-behaved' },
  '叱られる': { romaji: 'shikarareru', en: 'to be scolded / get told off', hiragana: 'しかられる', example: '親に叱られた', exampleEn: 'Got told off by my parents' },
  '気だるい': { romaji: 'kidarui', en: 'sluggish / listless / languid', hiragana: 'きだるい', example: '気だるい午後', exampleEn: 'A listless afternoon' },
  '眩しい': { romaji: 'mabushii', en: 'dazzling / blinding / radiant', hiragana: 'まぶしい', example: '眩しくて目が開けられない', exampleEn: 'So dazzling I can\'t open my eyes' },
  '懐かしい': { romaji: 'natsukashii', en: 'nostalgic / dear memories', hiragana: 'なつかしい', example: '懐かしい場所', exampleEn: 'A nostalgic place' },
  '正しい': { romaji: 'tadashii', en: 'correct / right / proper', hiragana: 'ただしい', example: '正しいことを言う', exampleEn: 'Say the right thing' },
  '洒落': { romaji: 'share', en: 'stylish / fashionable (in お洒落)', hiragana: 'しゃれ', example: 'お洒落が好き', exampleEn: 'Like being fashionable' },
  'お洒落': { romaji: 'oshare', en: 'fashionable / stylish / dressing up', hiragana: 'おしゃれ', example: 'お洒落して出かける', exampleEn: 'Get dressed up and go out' },
  'すっぴん': { romaji: 'suppin', en: 'bare face / no make-up', hiragana: 'すっぴん', example: 'すっぴんで会う', exampleEn: 'Meet without make-up on' },
  'フェス': { romaji: 'fesu', en: 'festival / music festival', hiragana: 'フェス', example: 'フェスに行こう', exampleEn: 'Let\'s go to the festival' },
  'ポケット': { romaji: 'poketto', en: 'pocket', hiragana: 'ポケット', example: 'ポケットに手を入れる', exampleEn: 'Put hands in pockets' },
  'バス': { romaji: 'basu', en: 'bus', hiragana: 'バス', example: 'バスに乗る', exampleEn: 'Ride the bus' },
  'フレーズ': { romaji: 'furēzu', en: 'phrase / lyric', hiragana: 'フレーズ', example: '好きなフレーズ', exampleEn: 'A favourite phrase' },

  // ── Remaining single kanji ──────────────────────────────────────
  '燃': { romaji: 'moeru', en: 'burn / blaze', hiragana: 'もえる', example: '夕焼けが燃える', exampleEn: 'The sunset blazes' },
  '家': { romaji: 'ie / uchi', en: 'house / home', hiragana: 'いえ', example: '家に帰る', exampleEn: 'Return home' },
  '帰': { romaji: 'kaeru', en: 'return / go home', hiragana: 'かえる', example: '早く帰ろう', exampleEn: 'Let\'s go home soon' },
  '無': { romaji: 'nai / mu', en: 'nothing / without / non-', hiragana: 'ない', example: '無駄にしない', exampleEn: 'Won\'t waste it' },
  '不': { romaji: 'fu', en: 'un- / not (negative prefix)', hiragana: 'ふ', example: '不安な気持ち', exampleEn: 'An uneasy feeling' },
  '的': { romaji: 'teki', en: '-like / -ish (suffix for adjectives)', hiragana: 'てき', example: '現実的に考える', exampleEn: 'Think realistically' },
  '的': { romaji: 'teki', en: '-like / -ish (suffix)', hiragana: 'てき', example: '音楽的センス', exampleEn: 'Musical sense' },
  '様': { romaji: 'yō / sama', en: 'like / as if / way / honorific', hiragana: 'よう', example: '夢の様だ', exampleEn: 'It\'s like a dream' },
  '歌': { romaji: 'uta', en: 'song / poem', hiragana: 'うた', example: '歌が好き', exampleEn: 'I love songs' },

  // ── Katakana loanwords from lyrics ─────────────────────────────
  'ウザい': { romaji: 'uzai', en: 'annoying / irritating (casual)', hiragana: 'うざい', example: 'ウザいほど来る', exampleEn: 'Comes in an annoyingly persistent way' },
  'フラッと': { romaji: 'furatto', en: 'casually / spontaneously / just dropping by', hiragana: 'ふらっと', example: 'フラッと現れる', exampleEn: 'Show up out of nowhere' },
  'スピード': { romaji: 'supīdo', en: 'speed', hiragana: 'スピード', example: '歩くスピード', exampleEn: 'Walking pace / speed' },
  'タイプ': { romaji: 'taipu', en: 'type / kind of person', hiragana: 'タイプ', example: '私のタイプじゃない', exampleEn: 'Not my type' },
  'キス': { romaji: 'kisu', en: 'kiss', hiragana: 'キス', example: 'キスをした', exampleEn: 'They kissed' },
  'ヒューマンドラマ': { romaji: 'hyūman dorama', en: 'human drama (TV/film genre)', hiragana: 'ヒューマンドラマ', example: 'つまらないヒューマンドラマ', exampleEn: 'A boring human drama' },
  'ダメ': { romaji: 'dame', en: 'no good / useless / not allowed', hiragana: 'だめ', example: 'もうダメだ', exampleEn: 'I\'m done for / it\'s no use' },
  'ケガ': { romaji: 'kega', en: 'injury / wound', hiragana: 'けが', example: 'ケガをした', exampleEn: 'I got injured' },
  '中': { romaji: 'naka / chū', en: 'inside / middle / among / throughout', hiragana: 'なか', example: '雨の中で歌う', exampleEn: 'Sing in the rain' },
  '捨': { romaji: 'suteru', en: 'throw away / abandon / discard', hiragana: 'すてる', example: '過去を捨てる', exampleEn: 'Leave the past behind' },
  '捨て猫': { romaji: 'suteneko', en: 'stray cat / abandoned cat', hiragana: 'すてねこ', example: '捨て猫を拾った', exampleEn: 'Picked up a stray cat' },
}));
